version: '3.8'

services:
  app:
    build:
      context: .
      # Use the development stage for local development
      target: development
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      # Mount source code for hot-reloading in development
      - .:/app
      - /app/node_modules # Prevent node_modules from being overwritten by host volume
    environment:
      # Pass environment variables from the host .env file
      - NODE_ENV=development
      - PORT=${PORT:-3000}
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017/aahaar}
      # Add other required variables here
      - JWT_SECRET=${JWT_SECRET:-changeme}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:4200}
    depends_on:
      - mongodb
    # Optional: Health check for the app
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"] # Adjust endpoint if needed
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      # Persist data
      - mongodb_data:/data/db
    # Optional: Health check for MongoDB
    # healthcheck:
    #   test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    restart: unless-stopped

volumes:
  mongodb_data:
